### ISSUE TITLE
We need to establish some rules and conventions

### ISSUE THREAD

**Issue by mklabs** [3monkeys/play.rules#1]
Regarding the repo structure... or the language used for commits message, files/folder name, etc.

Even though the book writen here is primary intended for the french language, this is generally a good practice to stick ourselves to use english for the rest (just like you normally don't mess french commentary/variable name in your own developments).

Feel free to tell `Fuck off Mickael`, on s'en fout, on écrit en frenchy.

**Comment by loicdescotte** [comment]
Ok for me, no pb

On Sun, Apr 3, 2011 at 11:40 AM, mklabs <
reply@reply.github.com>wrote:

> Regarding the repo structure... or the language used for commits message,
> files/folder name, etc.
> 
> Even though the book writen here is primary intended for the french
> language, this is generally a good practice to stick ourselves to use
> english for the rest (just like you normally don't mess french
> commentary/variable name in your own developments).
> 
> Feel free to tell `Fuck off Mickael`, on s'en fout, on crit en frenchy.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/3monkeys/play.rules/issues/1

## 

Loc Descotte
4 rue Joseph Fourier
38000 Grenoble

06 23 23 36 80

**Comment by k33g** [comment]
fuck, wir schreiben auf Französisch

**Comment by mklabs** [comment]
@k33g Président!

**Comment by k33g** [comment]
- on the one hand :

about newbee part aka "partie zero", it's me believe that it have to be "open bar".
- on the other hand :

more rigor does not kill ;) about part one, two, etc. ...

but we write for a French audience

my proposal :
- repo structure in english
- prefix : part, ch and book
- name of part and chapter : french (i know ...)
- commit : in english (in english "..." means "..." ;) )
- suppr .fr in file name

**Comment by loicdescotte** [comment]
#! convention 

After looking at Play website, I saw that the '!' is only used in the logo, not in the name of the framework.
Example : `The Play framework makes it easier to build Web applications with Java and Scala`
So we should remove all the '!' from the chapters in Play name.

For the var or method names in the text parts, I suggest to use _italic_
Example : The _save_ method is called in the controller to save an album

I've already started to do this on my chapters, I can update yours if you're OK with this conventions

**Comment by k33g** [comment]
- i love the **!** :(, but as you want
- i think it's easier to read "`save` method" than "_save_ method"

**Comment by loicdescotte** [comment]
sorry for the '!' , it's just to be right in the framework name 

ok, good idea for `this` , i will update my chapters

**Comment by k33g** [comment]
i will update my chapters too (i have to remember ;))
