### ISSUE TITLE
Port d'écoute

### ISSUE THREAD

**Issue by rakiz** [3monkeys/play.rules#11]
J'ai suivi le tuto, mais lorsque je me connectais sur le port par défaut (9000), rien ne répondait. Je l'ai changé (8080) et tout fonctionne. Je pense que je dois soit avoir un blocage de ce port, soit une autre appli qui écoute dessus.

Toujours est-il que prévoir ce cas dans le bouquin, et expliquer comment changer le port dans application.conf

**Comment by loicdescotte** [comment]
Bonne idée , il faudra surement faire une annexe avec les subtilités du fichier application.conf

**Comment by javathought** [comment]
Il faudrait plutôt le mettre tout de suite : c'est dans le chapitre 1 (l'initiation) et le lecteur découvre. Donc si il rencontre un problème tout de suite et doit fouiller pour trouver la réponse à son problème ça va pas le faire.

Par contre, on peut y faire une note sur l'annexe (future) sur application.conf.

**Comment by javathought** [comment]
On peut fermer, non?

**Comment by loicdescotte** [comment]
Thanks ;)
