### ISSUE TITLE
Intégration dans l'IDE

### ISSUE THREAD

**Issue by rakiz** [3monkeys/play.rules#12]
Vous ne parlez que de Idea, je pense que ca serait pas mal d'ajouter Eclipse (voir netbeans mais bon...)

**Comment by loicdescotte** [comment]
En fait logiquement ça ne change pas du tout la manière de développer, on prend idea qui est le plus simple selon nous mais dans l'idée c'est la même chose

**Comment by k33g** [comment]
Notre conseil c'est d'utiliser idea community, c'est l'ide qui fonctionne le mieux avec Play! Mais on fera une cht'ite note à un moment ou à un autre
