### ISSUE TITLE
Chapitre 01 - paragraphe Eclipse?

### ISSUE THREAD

**Issue by Baztoune** [3monkeys/play.rules#17]
Est-il intéressant de faire un paragraphe illustré de screenshots pour Eclipse, ou est-ce une volonté de simplifier le tutoriel?

**Comment by loicdescotte** [comment]
Effectivement c'était plutôt pour simplifier

2011/6/21 Baztoune <
reply@reply.github.com>

> Est-il intressant de faire un paragraphe illustr de screenshots pour
> Eclipse, ou est-ce une volont de simplifier le tutoriel?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/3monkeys/play.rules/issues/17

## 

Loc Descotte
4 rue Joseph Fourier
38000 Grenoble

06 23 23 36 80

**Comment by k33g** [comment]
j'ai même été méga fainéant sur le sujet (en + Eclispe et moi on n'est pas copains)

Mais oui c'est intéressant de le faire (je pense que je me ferais celui de NetBeans à l'occas)

**Comment by Baztoune** [comment]
Je veux bien m'occuper d'eclipse (surement ce week-end). Libre à vous de l'intégrer ensuite (pour ne pas surcharger le tuto, pourquoi ne pas mettre ça dans une annexe?)

**Comment by k33g** [comment]
je suis preneur sur l'annexe, tu as raison

2011/6/22 Baztoune <
reply@reply.github.com>

**Comment by loicdescotte** [comment]
Cool en plus j'ai quelques trucs  mettre en annexe moi aussi

On Wed, Jun 22, 2011 at 10:44 AM, k33g <
reply@reply.github.com>wrote:

> je suis preneur sur l'annexe, tu as raison
> 
> 2011/6/22 Baztoune <
> reply@reply.github.com>
> 
> > Je veux bien m'occuper d'eclipse (surement ce week-end). Libre  vous de
> > l'intgrer ensuite (pour ne pas surcharger le tuto, pourquoi ne pas mettre
> > a dans une annexe?)
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/3monkeys/play.rules/issues/17#issuecomment-1416612
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/3monkeys/play.rules/issues/17#issuecomment-1416664

## 

Loc Descotte
4 rue Joseph Fourier
38000 Grenoble

06 23 23 36 80

**Comment by 3monkeys** [comment]
oups, j'oublie tjrs de relever ce compte
désolé
