### ISSUE TITLE
Repo - File structure

### ISSUE THREAD

**Issue by mklabs** [3monkeys/play.rules#2]
Related [https://github.com/3monkeys/play.rules/issues#issue/1](https://github.com/3monkeys/play.rules/issues#issue/1)

If we want to have some kind of pdf/epub generation solution, we'll need to establish some rules and guidelines for the file structure (the same for the dynamic website to be generated).

Here are some examples here on github from which we could learn:
- [https://github.com/rmurphey/jqfundamentals](https://github.com/rmurphey/jqfundamentals)
- [https://github.com/visionmedia/masteringnode](https://github.com/visionmedia/masteringnode)

I really like the masteringnode approach. Anyway, both use a make generation system with tools like htmldoc and needs special configuration environments but I guess it's not a big deal.

**Comment by mklabs** [comment]
I like the way that jqfundamentals is structured [https://github.com/rmurphey/jqfundamentals/tree/master/book](https://github.com/rmurphey/jqfundamentals/tree/master/book)
- part1-part-name
  - ch01-chapter-name.md
  - ch02-chapter-name.md
- part2-part-name
  - ch03-chapter-name.md
- ...

No mixed hypen/underscore (Chapter2-name_of_chapter). Relatedly, file names should not have special char like `'` or blank spaces. Exact chapter name would be the first header in the md file where we could have more space to name the chapter the way we want.

**Comment by k33g** [comment]
Ich wähle diese Version "https://github.com/rmurphey/jqfundamentals" weil die Parteien und das Kapitel

**Comment by k33g** [comment]
Ist das "_" ist erlaubt

**Comment by k33g** [comment]
so ...
- book
  >> part0-je-suis-nul `ou part00 ?`
  >>> ch01-....
  >> part1-je-suis-pret
  >>etc. ..

ps. je tiens au _zero_, ça gêne ?
pour les images ? 1 seul rép ou 1 par chapitre ?

**Comment by mklabs** [comment]
close, plus d'actualité.
