### ISSUE TITLE
remove mklabs from contributors

### ISSUE THREAD

**Issue by mklabs** [3monkeys/play.rules#22]
not enough commits, no enough involvement to consider myself as a "contributor" for this project: remove mklabs from readme, front cover and such.

play.rules belongs to @loicdescotte and @k33g the guys really pushing this project forward.

I may have had the original idea, by pushing those two nice guys to begin play.rules but that's all. I've worked on things related to this project like the branch where the site would live, and a basic pdf generation process. But these are not what really matters in this project, articles in master.

I'll always be here to help, but my lack of involvement is a problem to me.

**Comment by loicdescotte** [comment]
Done
