### ISSUE TITLE
Some ideas for the front chapter

### ISSUE THREAD

**Issue by loicdescotte** [3monkeys/play.rules#3]
Juste some suggestions, to be validated by mklabs
- Explain how you made the "pretty vote" branch to prettify vote4music app (continuation of the part 02)
- Use WebSockets (included in Play 1.2 features) to show some "push" features 
- Show how to use the TSA architecture with Play REST services

**Comment by mklabs** [comment]
++++++++++1

**Comment by loicdescotte** [comment]
Cool!

**Comment by mklabs** [comment]
Not enough time and my energy is put extensively on other stuff than Play for now. Hard to write on stuff that you dont actually use seriously.

Closing it for now.
