### ISSUE TITLE
Le contenu du script est invisible dans le PDF

### ISSUE THREAD

**Issue by BrunoVernay** [3monkeys/play.rules#31]
ligne 189 de play.rules / livre / part01-je-suis-pret / ch01-l-application-vote4music.md

Le script est dans le source mais apparait en blanc sur fond blanc dans le PDF du 28/11/11 18:44. 
Page 54 / 119

**Comment by loicdescotte** [comment]
Merci je vais voir ce qui se passe!

2011/11/29 Bruno Vernay <
reply@reply.github.com

> ligne 189 de play.rules / livre / part01-je-suis-pret /
> ch01-l-application-vote4music.md
> 
> Le script est dans le source mais apparait en blanc sur fond blanc dans le
> PDF du 28/11/11 18:44.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/3monkeys/play.rules/issues/31

## 

Loc Descotte
4 rue Joseph Fourier
38000 Grenoble

06 23 23 36 80

**Comment by loicdescotte** [comment]
Bizarre dans github a s'affiche bien... philippe t'as une ide?

2011/11/29 Loic Descotte loic.descotte@gmail.com

> Merci je vais voir ce qui se passe!
> 
> 2011/11/29 Bruno Vernay <
> reply@reply.github.com
> 
> > ligne 189 de play.rules / livre / part01-je-suis-pret /
> > ch01-l-application-vote4music.md
> > 
> > Le script est dans le source mais apparait en blanc sur fond blanc dans
> > le PDF du 28/11/11 18:44.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/3monkeys/play.rules/issues/31
> 
> ## 
> 
> Loc Descotte
> 4 rue Joseph Fourier
> 38000 Grenoble
> 
> 06 23 23 36 80

## 

Loc Descotte
4 rue Joseph Fourier
38000 Grenoble

06 23 23 36 80

**Comment by loicdescotte** [comment]
ça semble ok maintenant!
