### ISSUE TITLE
Activation module CRUD: Remarque

### ISSUE THREAD

**Issue by tatemilio** [3monkeys/play.rules#32]
En lisant le eBook, j'ai une remarque (page 24 et 23).
Page 23 on explique comment activer le module CRUD via le fichier dependencies.yml en expliquant que le chargement via le fichier application.conf est déprécié depuis la version 1.2.1 et quant on lit la suite page 24 on passe par le fichier application.conf, cela est redondant et la méthode est dépréciée.

**Comment by loicdescotte** [comment]
Merci on va corriger!

**Comment by tatemilio** [comment]
En tout cas, bravo pour cette initiative, est-il prévu d'avoir une transposition à la version 2 de Play car j'ai le sentiment qu'il y a beaucoup de différence entre les deux version non ?

**Comment by loicdescotte** [comment]
Merci :-)
Pas sûr pour Play 2 ça va dépendre du temps qu'on a , pour la première version ça nous a pris beaucoup de temps et c'est un peu déprimant (du point de vue du bouquin) de voir que les API ont complètement changé dans version 2.0 ...

**Comment by k33g** [comment]
opus suis à la bourre dans la correction 
désolé
promis je vais m'y mettre
