### ISSUE TITLE
Version epub/mobi

### ISSUE THREAD

**Issue by chprome** [3monkeys/play.rules#33]
Une version ebook/mobi du bouquin est-elle prévue ?

**Comment by loicdescotte** [comment]
Pour l'ebook on a un pdf, et il y a aussi un site mobile.
Tout est dispo ici : http://3monkeys.github.com/play.rules/

2012/2/23 chprome <
reply@reply.github.com

> Une version ebook/mobi du bouquin est-elle prvue ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/3monkeys/play.rules/issues/33

## 

Loc Descotte
4 rue Joseph Fourier
38000 Grenoble

06 23 23 36 80

**Comment by chprome** [comment]
Ok merci, mais en fait l'idée est de pouvoir le lire sur un Kindle.
Il est possible de convertir le PDF mais le résultat est plus que moyen.

Peut-être existe-t-il un moyen de générer un epub directement à partir des sources ?

**Comment by loicdescotte** [comment]
C'est vrai qu'on a pas le format epub, en tout cas si quelqu'un sait
comment gnrer du epub  partir de fichiers markdown ou html toute
contribution est la bienvenue!

2012/2/23 chprome <
reply@reply.github.com

> Ok merci, mais en fait l'ide est de pouvoir le lire sur un Kindle.
> Il est possible de convertir le PDF mais le rsultat est plus que moyen.
> 
> Peut-tre existe-t-il un moyen de gnrer un epub directement  partir des
> sources ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/3monkeys/play.rules/issues/33#issuecomment-4135614

## 

Loc Descotte
4 rue Joseph Fourier
38000 Grenoble

06 23 23 36 80

**Comment by chprome** [comment]
[Pandoc](http://johnmacfarlane.net/pandoc/epub.html) fait ça à merveille !
Il faut juste écrire un script pour automatiser la conversion.

Du genre : 

```
#!/bin/bash
pandoc -S -o play-rules.epub title.txt 00-cover.md 01-Preface.md  etc...
```

**Comment by loicdescotte** [comment]
Ah c'est cool a! Je vais y jeter un oeil merci :)

On Thu, Feb 23, 2012 at 2:27 PM, chprome <
reply@reply.github.com

> wrote:
> 
> [Pandoc](http://johnmacfarlane.net/pandoc/epub.html) fait a  merveille !
> Il faut juste crire un script pour automatiser le conversion.
> 
> Du genre :
> 
> ```
> #!/bin/bash
> pandoc -S -o play-rules.epub title.txt 00-cover.md 01-Preface.md  etc...
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/3monkeys/play.rules/issues/33#issuecomment-4136166

## 

Loc Descotte
4 rue Joseph Fourier
38000 Grenoble

06 23 23 36 80

**Comment by loicdescotte** [comment]
Je viens d'essayer, ça ne va pas le faire au niveau du code tout est mis en vrac l'indentation n'est pas respectée... 
Ou alors il va falloir qu'on s'affranchisse des tags github pour la coloration syntaxique (bof)

**Comment by chprome** [comment]
En ce qui me concerne ça fonctionne très bien sur mon kindle (sans la couleur mais avec un niveau de gris)
Voici le rendu avec Calibre : http://tinypic.com/view.php?pic=2mws9t&s=5

Si besoin je peux envoyer le epub que j'ai obtenu.

**Comment by loicdescotte** [comment]
Ah oui c'est vraiment bien comme ça, ça doit venir du reader que j'ai utilisé (fbreader)
Si tu as une version complète d'ebook qui est nickel est ce que tu peux juste la déposer dans le répo git avec un pullrequest?

Merci d'avance :)

**Comment by k33g** [comment]
c'est en cours, merci @chprome
