### ISSUE TITLE
livre.play.deux.web > Les vues Scala: prise en compte par java et organisation 

### ISSUE THREAD

**Issue by rakiz** [3monkeys/play.rules#37]
Deux problèmes / questions pour le prx d'une:
1. Je rencontre pas mal de problèmes quand j'ajoute une nouvelle vue pour qu'elle soit correctement prise en compte et visible depuis java 'nom_de_la_vue.render()'. A chaque fois, je tripatouille, je rafraichi, je clean et pis pouf ca marche... Une idée du pourquoi du comment? Du coup, un petit paragraphe sur ce "problème" serait le bienvenu je pense.
2. Pour le moment, toutes les vues sont dans le même répertoire. Bon, mais si je veux organiser un peu tout ca genre séparer les écrans du FO et du BO? Je crée des sous-répertoires? Je fait face a mon pb N°1 et mes tripatouillages n'y changent rien...

**Comment by loicdescotte** [comment]
Hello,
Je n'ai jamais rencontré ton problème 1, peut être que ça vient simplement du temps de compilation?

Pour le 2 les répertoires des vues correspondent simplement aux noms de contrôleurs,  du coup pour séparer il te suffit de créer plusieurs contrôleurs.

Loic

**Comment by rakiz** [comment]
Je me rends compte qu'il n'est nul part fait mention de quelle version du livre je parle: je suis sur Play!2 (j'edit le titre)

Mon premier souci m'arrive a chaque fois (et j'ai un collègue qui a le même souci). J'ai même basculé d'Eclipse a IntelliJ: mon tripatouillage fonctionne beaucoup mieux avec Idea.
Quand au point 2, je n'ai pas de répertoire par controller, toutes les vues sont dans /app/views

Rencontres-tu égalment ce problème k33g? Ou je suis vraiment tout seul? (enfin avec mon collègue :) )

**Comment by loicdescotte** [comment]
Comme tu parlais de vues Scala j'en avais déduit que tu étais sur Play 2;)
Apparement c'est plutôt un problème lié à Eclipse alors? On utilise pas trop Eclipse à vrai dire :)

**Comment by k33g** [comment]
Hello,
pour le 1er point, je ne comprend pas trop, il faudrait que tu sois plus précis

sinon essaye ceci : en mode commande, tu vas dans le répertoire de ton projet, tu tapes play, une fois que tu as le prompt de la console play, tu tapes :  ~ run, à chaque fois que tu vas faire une modif et la sauvegarder ça va compiler automatiquement ton code, ça réglera peut être ton problème. Dis moi

pour le 2ème point, j'ai prévu un chapitre "organisation de code" mais je ne sais pas encore pour quand

pour l'ide j'utilise sublimeText2 sous windows et Linux, TexteMate sous OSX

**Comment by rakiz** [comment]
Le souci, c'est que quand j'ajoute un template, et que mes IDE (eclipse et IDEA) ne voulais pas les voir et me retournaient une erreur.
Eclipse a la facheuse tendance a mettre plein de trucs en cache et je pensais que ca venait de la. C'est pour ca que j'ai switché sur IDEA, mais ca faisait pareil. 

J'avais bataillé et bataillé ( Et mon collègue a eu les mêmes souci que moi).
Alors je relance tout pour vous détailler l'enchainement qui finit en erreur: impossible, TOUT fonctionnent.

Alors bon, j'arrete de vous embeter et je vais de ce pas poser des congés :)

Merci pour votre temps, on peut fermer l'issue.

**Comment by k33g** [comment]
LOL :) je crois que la prise en charge par les IDE n'est pas complètement au point, tu peut essayer de relancer un eclipsify ou un idealize peu être ?
c'est un peu pour ça que j'utilise juste un éditeur de texte (pourtant je suis pas un spécialise java mais avec play c'est jouable)
tu ne nous embêtes pas

bonnes vacances :)
