### ISSUE TITLE
public enum Genre { ROCK, METAL, ...

### ISSUE THREAD

**Issue by k33g** [3monkeys/play.rules#4]
Dans : ch01-L-application-vote4music/01-Mise-en-place-de-l-application.md

public enum Genre { ROCK, METAL, JAZZ, BLUES, POP, WORLD, HIP_HOP, OTHER }

tu devrais le mettre en mode code ou en mode ``

`public enum Genre { ROCK, METAL, JAZZ, BLUES, POP, WORLD, HIP_HOP, OTHER }`

**Comment by loicdescotte** [comment]
Merci je vais changer ça!

On Sun, Apr 24, 2011 at 7:43 PM, k33g <
reply@reply.github.com>wrote:

> Dans : ch01-L-application-vote4music/01-Mise-en-place-de-l-application.md
> 
> public enum Genre { ROCK, METAL, JAZZ, BLUES, POP, WORLD, HIP_HOP, OTHER }
> 
> tu devrais le mettre en mode code ou en mode ``
> 
> `public enum Genre { ROCK, METAL, JAZZ, BLUES, POP, WORLD, HIP_HOP, OTHER
> }`
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/3monkeys/play.rules/issues/4

## 

Loc Descotte
4 rue Joseph Fourier
38000 Grenoble

06 23 23 36 80

**Comment by loicdescotte** [comment]
C'est bizarre c'est bien en mode code, a s'affiche bien dans textmate mais
pas sous github

On Sun, Apr 24, 2011 at 9:05 PM, Loic Descotte loic.descotte@gmail.comwrote:

> Merci je vais changer a!
> 
> On Sun, Apr 24, 2011 at 7:43 PM, k33g <
> reply@reply.github.com>wrote:
> 
> > Dans : ch01-L-application-vote4music/01-Mise-en-place-de-l-application.md
> > 
> > public enum Genre { ROCK, METAL, JAZZ, BLUES, POP, WORLD, HIP_HOP, OTHER }
> > 
> > tu devrais le mettre en mode code ou en mode ``
> > 
> > `public enum Genre { ROCK, METAL, JAZZ, BLUES, POP, WORLD, HIP_HOP, OTHER
> > }`
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/3monkeys/play.rules/issues/4
> 
> ## 
> 
> Loc Descotte
> 4 rue Joseph Fourier
> 38000 Grenoble
> 
> 06 23 23 36 80

## 

Loc Descotte
4 rue Joseph Fourier
38000 Grenoble

06 23 23 36 80

**Comment by loicdescotte** [comment]
ça marche now

On Sun, Apr 24, 2011 at 9:07 PM, Loic Descotte loic.descotte@gmail.comwrote:

> C'est bizarre c'est bien en mode code, a s'affiche bien dans textmate mais
> pas sous github
> 
> On Sun, Apr 24, 2011 at 9:05 PM, Loic Descotte loic.descotte@gmail.comwrote:
> 
> > Merci je vais changer a!
> > 
> > On Sun, Apr 24, 2011 at 7:43 PM, k33g <
> > reply@reply.github.com>wrote:
> > 
> > > Dans : ch01-L-application-vote4music/01-Mise-en-place-de-l-application.md
> > > 
> > > public enum Genre { ROCK, METAL, JAZZ, BLUES, POP, WORLD, HIP_HOP, OTHER
> > > }
> > > 
> > > tu devrais le mettre en mode code ou en mode ``
> > > 
> > > `public enum Genre { ROCK, METAL, JAZZ, BLUES, POP, WORLD, HIP_HOP, OTHER
> > > }`
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/3monkeys/play.rules/issues/4
> > 
> > ## 
> > 
> > Loc Descotte
> > 4 rue Joseph Fourier
> > 38000 Grenoble
> > 
> > 06 23 23 36 80
> 
> ## 
> 
> Loc Descotte
> 4 rue Joseph Fourier
> 38000 Grenoble
> 
> 06 23 23 36 80

## 

Loc Descotte
4 rue Joseph Fourier
38000 Grenoble

06 23 23 36 80
