### ISSUE TITLE
Mise en forme code activation CRUD

### ISSUE THREAD

**Issue by Baztoune** [3monkeys/play.rules#6]
ch03-Premiere-application-CRUD.md 
paragraphe "Donc pour activer le module CRUD :"

Le code est  sur la même ligne que les commentaires (bullets+tabs+code n'ont pas l'air de bien cohabiter). 
ie : le lecteur va copier brut dans application.conf et ce ne sera pas pris en compte puisque tout sera sur la même ligne commentée

Je n'arrive pas à réparer ça dans mon fork sans casser la mise en forme. Je vous laisse ce soin :)

**Comment by Baztoune** [comment]
Note sur ce paragraphe : je n'ai pas compris l'intérêt d'importer \* /admin module:crud et GET /admin module:crud

**Comment by k33g** [comment]
- _intérêt d'importer \* /admin module:crud et GET /admin module:crud_ j'ai l'impression que cela joue sur le bandeau du haut (les liens pour naviguer) ... à creuser
- mise en page "fixed"

**Comment by mklabs** [comment]
Pas faux...

En fait, le problème vient des `>` et `>>` donnant des `<blockquote />`

```
> * aller dans `/azerguespeche/conf/application.conf`
> * ajouter ceci :

>> `# Import CRUD module`
>> `module.crud=${play.path}/modules/crud`

> * aller dans le fichier routes `/azerguespeche/conf/routes`
> * ajouter ceci :

>> `# Import CRUD routes`
>> `* /admin module:crud`

> * Et ceci : juste après `GET /   Application.index`

>> `GET /admin  module:crud`
```

Il n'y a aucne raison de définir cette liste avec des blockquote (certains imbriqués) dans le sens où un blockquote est conçu pour citer quelqu'un. Ici, ce n'est pas le cas. La gestion de snippets de code dans des listes peut être compliquée ac markdown, mieux vaut les éviter.

Devrait être quelque chose de plus simple du genre:

```
aller dans `/azerguespeche/conf/application.conf` et ajouter ceci :

    # Import CRUD module
    module.crud=${play.path}/modules/crud


aller dans le fichier routes `/azerguespeche/conf/routes` et ajouter ceci :

    # Import CRUD routes
    /admin module:crud

Et ceci : juste après `GET /   Application.index`

    GET /admin  module:crud
```

> Note sur ce paragraphe : je n'ai pas compris l'intérêt d'importer \* /admin module:crud et GET /admin module:crud

Très bonne remarque, j'imagine qu'il s'agit d'une petite coquille, si l'on importe `* /admin module:crud` (\* signifiant tt les verbes http), cela paraît un peu redondant avec `GET /admin  module:crud` ([HTTP routing](http://www.playframework.org/documentation/1.2/routes#anamesyntaxTheroutesfilesyntaxa))

Merci Bastien, tes relectures et retours sont toujours très appréciés.

**Comment by mklabs** [comment]
Petit ajout: http://github.github.com/github-flavored-markdown/ github modifie un peu le parsing classique markdown pour permettre deux trois trucs bien sympas, dont la possibilité de gérer convenablement ce genre de cas

```
What about some code **in** a list? That's insane, right?

* In Ruby you can map like this:

        ['a', 'b'].map { |x| x.uppercase }

* In Rails, you can do a shortcut:

        ['a', 'b'].map(&:uppercase)
```

What about some code **in** a list? That's insane, right?
- In Ruby you can map like this:
  
  ```
  ['a', 'b'].map { |x| x.uppercase }
  ['a', 'b'].map { |x| x.uppercase }
  ```
- In Rails, you can do a shortcut:
  
  ```
  ['a', 'b'].map(&:uppercase)
  ```

**Comment by k33g** [comment]
c'était juste pour faire joli (les barres) ...

pour les routes, touchez à rien, je ferais des tests pdt mes congés, mais dans le module CRUD ça a une influence
je vous tiens au courant

**Comment by k33g** [comment]
pour les routes :

1- j'importe
2- je déclare

mais promis je testerais

**Comment by k33g** [comment]
si j'enlève : GET /admin  module:crud

puis que je vais sur [http://localhost:9000/pecheurs/list](http://localhost:9000/pecheurs/list)
puis que je clique en haut sur "Home", j'obtiens une joli "access denied"

si je garde : GET /admin  module:crud et que j'enlève : \* /admin module:crud
ça fonctionne

pourtant j'ai bien tiré ça de quelque part ...

Loïc, avant que je fasse la correction, tu aurais une idée sur le sujet ?

**Comment by loicdescotte** [comment]
Oups j'avais pas vu la question, non pas d'idée à froid comme ça désolé

**Comment by k33g** [comment]
à priori ils ont raison (j'ai testé), je chercherais un peu plus lorsque que je vais rédiger la suite
